### ISSUE TITLE
Common theme deploy issue

### ISSUE THREAD

**Issue by sivakon** [tlienart/FranklinTemplates.jl#51] opened 2020-04-20 06:20 UTC
Even though I put `hasmath=true`, `katex.min.js` is not being added to generated HTML. When I `serve()` locally, this works fine. I fixed temporarily by eliminating if blocks from `_layouts/head.html`

Markdown
https://github.com/sivakon/sivakon.github.io/blob/766c26f8208e184fa738d8aafb5174631b0a8b6e/gp.md

Generated HTML
https://github.com/sivakon/sivakon.github.io/blob/aa8a06c5d7281de2d4af5c91d5b3840fc3f5004c/gp/index.html

**Comment by tlienart** [comment] 2020-04-20 07:55
Hello @sivakon I need a bit more info: how do you push stuff ? do you use `publish`? if so there's a prerendering step which takes all your KaTeX, pre-generates it to HTML, serves that and **doesn't** load the katex file as a result as it's not needed.

If you don't want this to happen, use `publish(prerender=false)`, or, if you use the github-action route, make sure the last command is `optimize(prerender=false)`.

Let me know if that helps

**Comment by tlienart** [comment] 2020-04-20 07:56
for instance: https://tlienart2.github.io/ if you look at the HTML the `js` file is not there but the math is rendered.

**Comment by sivakon** [comment] 2020-04-21 05:50
The latex actually renders but there is extra math that shows up along with it on the website.

Look at the difference between this
https://kons.dev/blogtmp/gp/
REPO -  https://github.com/sivakon/blogtmp


<img width="726" alt="Screen Shot 2020-04-21 at 14 49 15" src="https://user-images.githubusercontent.com/1740785/79829994-6eea0e80-83df-11ea-8d2d-5bff0ca77f4c.png">


https://kons.dev/gp/
REPO - https://github.com/sivakon/sivakon.github.io

**Comment by tlienart** [comment] 2020-04-21 07:10
Thanks for  pointing to the repo, give me a few minutes and I'll see what I can do

**Comment by tlienart** [comment] 2020-04-21 07:41
Ok I can reproduce the issue, there are two things happening it seems

1. it seems the prerendering step does not work as it shoul
2. there seems to be a glitch with automatic math detection in Franklin

I'll get back when I have a fix.

**Comment by tlienart** [comment] 2020-04-21 07:47
Ok so that's fixed: https://tlienart.github.io/blogtmp2/gp/ 

The issue is with `automath` and `autocode`. For now, if you put

```
@def automath = false
@def autocode = false
```

and leave the rest as it was, things should just work.

A patch fixing the issue with auto will be in soon. Thanks.

**Comment by tlienart** [comment] 2020-04-21 08:15
Now fixed in 0.7.5; kindly let me know if you have more issues with this and sorry for the inconvenience.

**Closed** 2020-04-21 08:15 UTC

**Comment by sivakon** [comment] 2020-04-22 05:40
Thanks so much for your time. I am gonna try the new version.
